Parameters:
  EnvironmentName:
    Description: Environment Name
    Type: String
    AllowedValues: [development, production]
    ConstraintDescription: must be development or production
Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-04ad2567c9e3d7893
    us-east-2:
      HVM64: ami-0dd0ccab7e2801812
    us-west-1:
      HVM64: ami-0074ef78ecb07948c
    us-west-2:
      HVM64: ami-00be885d550dcee43
  EnvironmentToInstanceType:
    development:
      instanceType: t2.micro
    production:
      instanceType: t2.small
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref 'EnvironmentName', instanceType]
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', HVM64]