Parameters:
  ApplicationName:
    Description: Yasol's application name desu
    Type: String
  VPCId:
    Description: VPC to create the SG into
    Type: AWS::EC2::VPC::Id

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Security group for ${ApplicationName}
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/25"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          Description: SSH for Engineering department
        - CidrIp: "192.168.0.0/25"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          Description: SSH for HR department
      VpcId: !Ref VPCId
Outputs:
  SSHGroupId:
    Value:  !Ref SSHSecurityGroup
    Description: Id for the SSH Security Group